### ISSUE TITLE
LilyGO TTGO T3 LoRa32 868MHz V1.6.1  board + a Vevor 7 in 1 weather station.

### ISSUE THREAD

**Issue by cipriancu** [juanboro/rtl_433_Decoder_ESP#2]
Hello. i have the following setup. ESPhome on homeassistant + a LilyGO TTGO T3 LoRa32 868MHz V1.6.1  board + a Vevor 7 in 1 weather station. And I would like to be able to read information from Vevor via ESPHome. (I tried over openMQTT, but there are some errors )  Firstly, I managed to read raw data from Vevor by using swoboda1337 driver for sx127x  

external_components:
  - source: github://swoboda1337/sx127x-esphome@main
    components: [ sx127x ]

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO27
  miso_pin: GPIO19

sx127x:
  cs_pin: GPIO18
  rst_pin: GPIO23
  bandwidth: 50_0kHz
  frequency: 868350000
  modulation: FSK
  packet_mode: false
  rx_start: true
  sync_value: [0xCA, 0xCA, 0x54, 0xAA]
  crc_enable: true

remote_receiver:
  pin:
    number: GPIO32
    inverted: true
  dump: all

And this is how raw data looks like 

[07:35:28][D][remote.beo4:086]: Beo4: n_sym=85
[07:35:28][I][remote.pronto:231]: Received Pronto: data=
[07:35:28][I][remote.pronto:233]: 0000 006D 002B 0000 0006 0016 000E 0011 0003 0006 0005 0007 0005 0010 000A 0010 0003 0002 0003 0011 0007 0008 0008 000C 0003 0012 0004 0025 0005 0002 0007 0009 0004 000A 000B 000A 000A 0016 0003 0006 0007 0044 0003 0013 0004 0004 
[07:35:28][I][remote.pronto:233]: 0008 0004 0008 0004 0004 0010 0007 0011 0007 0028 0004 001B 0003 0003 0007 0008 0003 0006 000B 0018 0006 0009 0003 0003 0004 0022 0007 0017 0003 000A 0003 0012 0005 000C 0005 000B 000C 0005 000E 001B 0003 000E 0181 
[07:35:48][D][remote.beo4:086]: Beo4: n_sym=88
[07:35:48][I][remote.pronto:231]: Received Pronto: data=
[07:35:48][I][remote.pronto:233]: 0000 006D 002C 0000 000D 0003 001E 0005 000A 0003 0014 0007 0009 0009 001B 0003 0005 0003 0011 000A 001C 0003 0015 0006 0009 0006 0021 0004 0002 0007 0007 0003 0014 0003 0022 0003 0002 0004 000D 0003 000D 0004 0002 0003 0019 0008 
[07:35:48][I][remote.pronto:233]: 0002 0003 0004 0004 0018 0005 0008 0003 0004 0006 0021 0003 0006 0009 0004 000D 0004 0004 0007 0008 0012 0004 001C 0003 0012 0005 0013 0006 000A 0009 0008 0003 0004 0008 0022 0005 0016 0005 000D 0003 0004 0003 0001 0003 0017 0181 
[07:36:08][D][remote.beo4:086]: Beo4: n_sym=89
[07:36:08][I][remote.pronto:231]: Received Pronto: data=
[07:36:08][I][remote.pronto:233]: 0000 006D 002D 0000 000C 000F 0007 000A 0004 0002 0008 0004 0007 0009 0004 0007 0005 0003 0006 0011 000E 0018 0003 0002 0003 0003 0004 0025 0006 0035 0003 002F 000B 0004 000B 0004 0008 0011 0003 000E 0007 0022 0008 0012 0003 000A 
[07:36:08][I][remote.pronto:233]: 0003 0007 000B 0014 0005 0001 0009 0007 0008 0002 0004 0003 0004 000C 0006 000B 0006 0003 000C 002B 0007 0011 0003 0001 0003 000A 0008 0005 0005 000B 0005 0034 0003 000B 0004 0003 0003 0001 0003 0028 0008 0002 0005 0010 0004 000F 
[07:36:08][I][remote.pronto:233]: 0181 
[07:36:28][D][remote.beo4:086]: Beo4: n_sym=106
[07:36:28][I][remote.pronto:231]: Received Pronto: data=
[07:36:28][I][remote.pronto:233]: 0000 006D 0035 0000 0049 0003 0008 0004 0006 0006 000E 0005 000A 0004 0011 0004 0002 0003 0013 0003 0016 000C 0003 0007 0007 0006 0003 0007 0005 0010 000D 0005 0009 0007 000D 0003 0025 0008 0002 0004 000A 0003 0002 0003 0003 0005 
[07:36:28][I][remote.pronto:233]: 0008 0005 0018 000E 000E 0003 0008 0003 0005 0004 0003 0009 000A 0005 0001 0004 001D 0004 0006 0004 001B 0004 0004 0003 0008 0005 0016 0005 0012 0004 000A 0009 0007 0003 0002 0003 0004 000B 0008 0003 0003 000C 0004 0004 0002 0003 
[07:36:28][I][remote.pronto:233]: 0002 0003 0035 0006 0006 0007 0002 000C 0003 0005 001C 0007 000D 0005 0006 0006 0005 0181 

I think the next step is to use your code somehow to decode the raw data received, but  I'm stuck 

Please, can you guide me?

**Comment by juanboro** [comment]
>Please, can you guide me?

Sure.  For ESPHOME --- I've created a component here: [esphome-rtl_433-decoder](https://github.com/juanboro/esphome-rtl_433-decoder) .  So for your example above, you should just need to make the following modifications/additions (add this repo to external components, and add a rtl_433 configuration mapping to the yaml):

```yaml
external_components:
  - source: github://swoboda1337/sx127x-esphome@main
    components: [ sx127x ]
  - source: github://juanboro/esphome-rtl_433-decoder
    components: [ rtl_433 ]

spi:
  clk_pin: GPIO5
  mosi_pin: GPIO27
  miso_pin: GPIO19

sx127x:
  cs_pin: GPIO18
  rst_pin: GPIO23
  bandwidth: 50_0kHz
  frequency: 868350000
  modulation: FSK
  packet_mode: false
  rx_start: true
  sync_value: [0xCA, 0xCA, 0x54, 0xAA]
  crc_enable: true

remote_receiver:
  id: rf_receiver
  pin:
    number: GPIO32
    inverted: true
 #dump: all

rtl_433:
  id: my_rtl433_id
  receiver_id: rf_receiver
  on_json_message: 
    then:
      # do stuff with Arduino JSON message in 'x'.  
      # For example: https://github.com/juanboro/esphome-rtl_433-decoder/blob/main/examples/esp32-rtl_433-decoder.yaml 
      # or the sensor example: https://github.com/juanboro/esphome-rtl_433-decoder/blob/main/examples/esp32-rtl_433-sensors.yaml
      # see also esphome mqtt docs about on_json_message: https://esphome.io/components/mqtt.html 

```

If you run into any issues or need more help - add another issue over in the [esphome-rtl_433-decoder](https://github.com/juanboro/esphome-rtl_433-decoder) repo.
